services:
  mysql:
    container_name: 'mysql'
    image: 'mysql:latest'
    restart: 'always'
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_DATABASE=blog'
      - 'MYSQL_USER=admin'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=admin'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
